### ISSUE TITLE
I FEEL YOU BRO!

### ISSUE THREAD

**Issue by mdvsh** [soumitradev/Quiz#1]
![](https://media.giphy.com/media/XAN3IhajQymfS/giphy.gif)

**Comment by soumitradev** [comment]
Nice issue. I will try my best to implement the changes suggested in the next commit. Thanks for pointing out the numerous bugs this code has. If it weren't for you, this code would have gone into production and caused massive havoc. If you could open a Pull Request fixing these issues, that would be great. In fact, I might consider sponsoring you on GitHub for this. Keep up the great work!

P.S. I know this is not funny, and you didn't laugh.

**Comment by mdvsh** [comment]
#2 Closes this.
